# University Of Engineering And Technology Peshawar (Nowshera Campus).

Student Name: MUNSIFF ALI

Reg No:       22JZELE0489

### Introduction To Pandas Module
Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.
### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [5]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\envs\ml\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\admin\anaconda3\envs\ml\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\envs\ml\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\envs\ml\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\envs\ml\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\envs\ml\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Other way to install
If the above steps do not work for you, here is another way to install:<br>
Step 1: Go to your browser. Search for __python unofficial binaries__, or click <br>
https://www.lfd.uci.edu/~gohlke/pythonlibs/<br> 
and you will be redirected to the binary page.<br>
Step 2: To download the library, search for pandas – Ctrl + F will help you. Download pandas library based on your python version. <br>
Step 3: After the installation, head over to the directory where you've downloaded the pandas. <br>
Step 4: Right-click to open Windows PowerShell. Pip can help us with the installation. Just go to that location in your terminal and run the following command: <br>
__pip install pandas__ <br>
Complete this command by the TAB button so that the location of your folder is mentioned.

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [6]:
import pandas

In [7]:
students = {
    'Name': ["Muhammad Ayub ", " Ibraheem khan", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [8]:
df = pandas.DataFrame(students)

In [9]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(students)

In [12]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [13]:
pd.__version__

'2.3.3'

## Saving to CSV and other extensions like excel

In [14]:
df.to_csv('pythonMonday.csv')

## Remove Index and saving the csv file

In [15]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [16]:
df.head()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## Specify No of rows to show

In [17]:
df.head(3)

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19

In [18]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [19]:
df.tail()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [20]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

# Reading csv or other files

In [21]:
classData= pd.read_csv("pythonMondayRemoveIndex.csv")
classData

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [22]:
classData= pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [23]:
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

In [24]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [25]:
classData.drop(0, axis=0)

   Unnamed: 0            Name  Marks     Class  Age
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [26]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

# Check the spelling

In [27]:
classData['class']

KeyError: 'class'

# Check the trail space

In [ ]:
classData['Class ']

# Corrected Spelling

In [ ]:
classData['Name']

# Check the head space

In [ ]:
classData['Name']

In [ ]:
type(classData['Name'])

In [ ]:
classData['Age']

classData['gpa'][0]

In [ ]:
classData['Age'][0]

In [ ]:
classData['Age'][0]=90

In [ ]:
classData

In [ ]:
classData['Age'][4]

In [ ]:
classData['Age'][4]=5

In [ ]:
classData["Name"][4]

# Rename the column name

In [ ]:
classData.rename(columns={'Age': 'AGE'})

   Unnamed: 0            Name  Marks     Class  AGE
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

## Create Labels
With the index argument, you can name your own labels.

In [ ]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]
classData

        Unnamed: 0            Name  Marks     Class  Age
First            0  Muhammad Ayub      80  1st Year   20
Second           1   Ibraheem khan     72  2nd Year   21
Third            2   Muhammad Abid     77  1st Year   19
Fourth           3    Shumail Khan     65  3rd Year   22
Fifth            4       Qasim Ali     15  2nd Year   21

# Asignment

In [ ]:
classdata = classData.drop('Unnamed: 0', axis=1)
classData

        Unnamed: 0            Name  Marks     Class  Age
First            0  Muhammad Ayub      80  1st Year   20
Second           1   Ibraheem khan     72  2nd Year   21
Third            2   Muhammad Abid     77  1st Year   19
Fourth           3    Shumail Khan     65  3rd Year   22
Fifth            4       Qasim Ali     15  2nd Year   21

# Inplace

In [ ]:
classData.drop('Unnamed: 0', axis=1, inplace = True)
classData

                  Name  Marks     Class  Age
First   Muhammad Ayub      80  1st Year   20
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year   21

# Accessing the value in Dataframe

In [ ]:
classData["Name"]

First     Muhammad Ayub
Second     Ibraheem khan
Third      Muhammad Abid
Fourth      Shumail Khan
Fifth          Qasim Ali
Name: Name, dtype: object

In [ ]:
classData["Name"]["Fifth"]

'Qasim Ali'

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [ ]:
classData['Age']

First     20
Second    21
Third     19
Fourth    22
Fifth     21
Name: Age, dtype: int64

In [ ]:
 type(classData['Age'])

pandas.core.series.Series

In [ ]:
classData

                  Name  Marks     Class  Age
First   Muhammad Ayub      80  1st Year   20
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year   21

In [ ]:
type(classData)

pandas.core.frame.DataFrame

In [ ]:
import numpy as np

In [ ]:
series1= pd.Series(np.random.rand())

In [ ]:
series1

0    0.930359
dtype: float64

In [ ]:
series1= pd.Series(np.random.rand(30))

In [ ]:
series1

0     0.219437
1     0.156456
2     0.452832
3     0.217954
4     0.311333
5     0.656774
6     0.023840
7     0.048917
8     0.524419
9     0.505037
10    0.047261
11    0.021858
12    0.032108
13    0.174152
14    0.439369
15    0.633202
16    0.609018
17    0.794764
18    0.556220
19    0.251736
20    0.856955
21    0.905392
22    0.664004
23    0.883936
24    0.815843
25    0.723953
26    0.402616
27    0.860085
28    0.140358
29    0.962529
dtype: float64

In [ ]:
type(series1)

pandas.core.series.Series

In [ ]:
np.random.rand(3,4)

array([[0.51689487, 0.03764981, 0.14711555, 0.09957506],
       [0.83041878, 0.52850745, 0.38807532, 0.52423714],
       [0.43499759, 0.86252284, 0.44701721, 0.51993008]])

In [ ]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

In [ ]:
type(newDf)

pandas.core.frame.DataFrame

In [ ]:
newDf.head(2)

          0         1         2         3         4
0  0.023062  0.301940  0.771680  0.202020  0.656365
1  0.658970  0.900188  0.972621  0.359747  0.668194

In [ ]:
newDf.tail(2)

            0         1         2         3         4
328  0.230852  0.323425  0.439188  0.278900  0.467176
329  0.773845  0.870121  0.441973  0.701273  0.098071

In [ ]:
newDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       330 non-null    float64
 1   1       330 non-null    float64
 2   2       330 non-null    float64
 3   3       330 non-null    float64
 4   4       330 non-null    float64
dtypes: float64(5)
memory usage: 13.0 KB

In [ ]:
newDf.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.492586    0.515913    0.525078    0.464776    0.479341
std      0.277699    0.289276    0.290155    0.289494    0.285238
min      0.002119    0.007215    0.003138    0.006095    0.000597
25%      0.256995    0.276832    0.277944    0.207516    0.212980
50%      0.490712    0.524730    0.515311    0.447519    0.475194
75%      0.703390    0.787324    0.795302    0.686743    0.696778
max      0.993813    0.997368    0.999823    0.993332    0.997358

In [ ]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

# Change the value inside the dataframe

In [ ]:
newDf[0][0]= 10000.0

C:\Users\Admin\AppData\Local\Temp\ipykernel_11964\1615845312.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDf[0][0]= 10000.0

In [ ]:
newDf

                0         1         2         3         4
0    10000.000000  0.301940  0.771680  0.202020  0.656365
1        0.658970  0.900188  0.972621  0.359747  0.668194
2        0.052816  0.237507  0.683104  0.132024  0.382411
3        0.333242  0.016530  0.955146  0.443505  0.456245
4        0.618242  0.121679  0.217766  0.568361  0.752048
..            ...       ...       ...       ...       ...
325      0.141274  0.691162  0.008050  0.106659  0.537983
326      0.101747  0.787978  0.904832  0.976442  0.197264
327      0.524458  0.681397  0.861473  0.184172  0.259253
328      0.230852  0.323425  0.439188  0.278900  0.467176
329      0.773845  0.870121  0.441973  0.701273  0.098071

[330 rows x 5 columns]

In [ ]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.301940  0.771680  0.202020  0.656365
1      0.658970  0.900188  0.972621  0.359747  0.668194
2      0.052816  0.237507  0.683104  0.132024  0.382411
3      0.333242  0.016530  0.955146  0.443505  0.456245
4      0.618242  0.121679  0.217766  0.568361  0.752048

# Transpose

In [ ]:
newDf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,10000.000000,0.658970,0.052816,0.333242,0.618242,0.682891,0.753148,0.859956,0.966798,0.484740,...,0.221350,0.002119,0.085175,0.133480,0.136073,0.141274,0.101747,0.524458,0.230852,0.773845
1,0.301940,0.900188,0.237507,0.016530,0.121679,0.317867,0.573965,0.377479,0.983487,0.642936,...,0.169587,0.246019,0.381933,0.637954,0.020628,0.691162,0.787978,0.681397,0.323425,0.870121
2,0.771680,0.972621,0.683104,0.955146,0.217766,0.105667,0.828949,0.184769,0.856749,0.896735,...,0.517737,0.003138,0.422902,0.867242,0.967749,0.008050,0.904832,0.861473,0.439188,0.441973
3,0.202020,0.359747,0.132024,0.443505,0.568361,0.634197,0.399041,0.291622,0.650740,0.646278,...,0.374603,0.219945,0.967454,0.404461,0.058312,0.106659,0.976442,0.184172,0.278900,0.701273
4,0.656365,0.668194,0.382411,0.456245,0.752048,0.572066,0.495472,0.933162,0.064647,0.021737,...,0.387994,0.367198,0.575485,0.900415,0.615430,0.537983,0.197264,0.259253,0.467176,0.098071

# Sorting

In [ ]:
newDf.sort_index(axis=0)

                0         1         2         3         4
0    10000.000000  0.301940  0.771680  0.202020  0.656365
1        0.658970  0.900188  0.972621  0.359747  0.668194
2        0.052816  0.237507  0.683104  0.132024  0.382411
3        0.333242  0.016530  0.955146  0.443505  0.456245
4        0.618242  0.121679  0.217766  0.568361  0.752048
..            ...       ...       ...       ...       ...
325      0.141274  0.691162  0.008050  0.106659  0.537983
326      0.101747  0.787978  0.904832  0.976442  0.197264
327      0.524458  0.681397  0.861473  0.184172  0.259253
328      0.230852  0.323425  0.439188  0.278900  0.467176
329      0.773845  0.870121  0.441973  0.701273  0.098071

[330 rows x 5 columns]

In [ ]:
newDf.sort_index(axis=0, ascending=False)

                0         1         2         3         4
329      0.773845  0.870121  0.441973  0.701273  0.098071
328      0.230852  0.323425  0.439188  0.278900  0.467176
327      0.524458  0.681397  0.861473  0.184172  0.259253
326      0.101747  0.787978  0.904832  0.976442  0.197264
325      0.141274  0.691162  0.008050  0.106659  0.537983
..            ...       ...       ...       ...       ...
4        0.618242  0.121679  0.217766  0.568361  0.752048
3        0.333242  0.016530  0.955146  0.443505  0.456245
2        0.052816  0.237507  0.683104  0.132024  0.382411
1        0.658970  0.900188  0.972621  0.359747  0.668194
0    10000.000000  0.301940  0.771680  0.202020  0.656365

[330 rows x 5 columns]

In [ ]:
newDf.sort_index(axis=1)

                0         1         2         3         4
0    10000.000000  0.301940  0.771680  0.202020  0.656365
1        0.658970  0.900188  0.972621  0.359747  0.668194
2        0.052816  0.237507  0.683104  0.132024  0.382411
3        0.333242  0.016530  0.955146  0.443505  0.456245
4        0.618242  0.121679  0.217766  0.568361  0.752048
..            ...       ...       ...       ...       ...
325      0.141274  0.691162  0.008050  0.106659  0.537983
326      0.101747  0.787978  0.904832  0.976442  0.197264
327      0.524458  0.681397  0.861473  0.184172  0.259253
328      0.230852  0.323425  0.439188  0.278900  0.467176
329      0.773845  0.870121  0.441973  0.701273  0.098071

[330 rows x 5 columns]

In [ ]:
newDf.sort_index(axis=1, ascending=False)

            4         3         2         1             0
0    0.656365  0.202020  0.771680  0.301940  10000.000000
1    0.668194  0.359747  0.972621  0.900188      0.658970
2    0.382411  0.132024  0.683104  0.237507      0.052816
3    0.456245  0.443505  0.955146  0.016530      0.333242
4    0.752048  0.568361  0.217766  0.121679      0.618242
..        ...       ...       ...       ...           ...
325  0.537983  0.106659  0.008050  0.691162      0.141274
326  0.197264  0.976442  0.904832  0.787978      0.101747
327  0.259253  0.184172  0.861473  0.681397      0.524458
328  0.467176  0.278900  0.439188  0.323425      0.230852
329  0.098071  0.701273  0.441973  0.870121      0.773845

[330 rows x 5 columns]

In [ ]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.301940  0.771680  0.202020  0.656365
1      0.658970  0.900188  0.972621  0.359747  0.668194
2      0.052816  0.237507  0.683104  0.132024  0.382411
3      0.333242  0.016530  0.955146  0.443505  0.456245
4      0.618242  0.121679  0.217766  0.568361  0.752048

In [ ]:
newDf[0][1]

0.6589704102786864

In [ ]:
type(newDf[0])

pandas.core.series.Series

In [ ]:
newDf

                0         1         2         3         4
0    10000.000000  0.301940  0.771680  0.202020  0.656365
1        0.658970  0.900188  0.972621  0.359747  0.668194
2        0.052816  0.237507  0.683104  0.132024  0.382411
3        0.333242  0.016530  0.955146  0.443505  0.456245
4        0.618242  0.121679  0.217766  0.568361  0.752048
..            ...       ...       ...       ...       ...
325      0.141274  0.691162  0.008050  0.106659  0.537983
326      0.101747  0.787978  0.904832  0.976442  0.197264
327      0.524458  0.681397  0.861473  0.184172  0.259253
328      0.230852  0.323425  0.439188  0.278900  0.467176
329      0.773845  0.870121  0.441973  0.701273  0.098071

[330 rows x 5 columns]

## view

In [ ]:
newDfView=newDf

In [ ]:
newDfView

                0         1         2         3         4
0    10000.000000  0.301940  0.771680  0.202020  0.656365
1        0.658970  0.900188  0.972621  0.359747  0.668194
2        0.052816  0.237507  0.683104  0.132024  0.382411
3        0.333242  0.016530  0.955146  0.443505  0.456245
4        0.618242  0.121679  0.217766  0.568361  0.752048
..            ...       ...       ...       ...       ...
325      0.141274  0.691162  0.008050  0.106659  0.537983
326      0.101747  0.787978  0.904832  0.976442  0.197264
327      0.524458  0.681397  0.861473  0.184172  0.259253
328      0.230852  0.323425  0.439188  0.278900  0.467176
329      0.773845  0.870121  0.441973  0.701273  0.098071

[330 rows x 5 columns]

In [ ]:
newDfView[0][0]=765

C:\Users\Admin\AppData\Local\Temp\ipykernel_11964\4063526219.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfView[0][0]=765

In [ ]:
newDf.head()

            0         1         2         3         4
0  765.000000  0.301940  0.771680  0.202020  0.656365
1    0.658970  0.900188  0.972621  0.359747  0.668194
2    0.052816  0.237507  0.683104  0.132024  0.382411
3    0.333242  0.016530  0.955146  0.443505  0.456245
4    0.618242  0.121679  0.217766  0.568361  0.752048

In [ ]:
newDfView.head()

            0         1         2         3         4
0  765.000000  0.301940  0.771680  0.202020  0.656365
1    0.658970  0.900188  0.972621  0.359747  0.668194
2    0.052816  0.237507  0.683104  0.132024  0.382411
3    0.333242  0.016530  0.955146  0.443505  0.456245
4    0.618242  0.121679  0.217766  0.568361  0.752048

In [ ]:
newDfCopy=newDf.copy()

In [ ]:
newDfCopy[0][0]=656

C:\Users\Admin\AppData\Local\Temp\ipykernel_11964\2532441962.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfCopy[0][0]=656

In [ ]:
newDf.head()

            0         1         2         3         4
0  765.000000  0.301940  0.771680  0.202020  0.656365
1    0.658970  0.900188  0.972621  0.359747  0.668194
2    0.052816  0.237507  0.683104  0.132024  0.382411
3    0.333242  0.016530  0.955146  0.443505  0.456245
4    0.618242  0.121679  0.217766  0.568361  0.752048

In [ ]:
newDfCopy.head()

            0         1         2         3         4
0  656.000000  0.301940  0.771680  0.202020  0.656365
1    0.658970  0.900188  0.972621  0.359747  0.668194
2    0.052816  0.237507  0.683104  0.132024  0.382411
3    0.333242  0.016530  0.955146  0.443505  0.456245
4    0.618242  0.121679  0.217766  0.568361  0.752048

In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {
    "Student": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   Student  Marks  Age
0     Ali     85   20
1    Sara     92   21
2   Bilal     76   19
3    Hina     89   22

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      object
 1   Marks    4 non-null      int64
 2   Age      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None

In [ ]:
print("\nDescribe:\n", df.describe())

Describe:
            Marks        Age
count   4.000000   4.000000
mean   85.500000  20.500000
std     6.952218   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    87.000000  20.500000
75%    89.750000  21.250000
max    92.000000  22.000000

In [ ]:
# -----------------------------
# 2. SORTING
# -----------------------------
print("\nSorting by Marks (descending):\n", df.sort_values("Marks", ascending=False))
print("\nSorting by Age (ascending):\n", df.sort_values("Age"))

Sorting by Marks (descending):
   Student  Marks  Age
1    Sara     92   21
3    Hina     89   22
0     Ali     85   20
2   Bilal     76   19

Sorting by Age (ascending):
   Student  Marks  Age
2   Bilal     76   19
0     Ali     85   20
1    Sara     92   21
3    Hina     89   22

In [ ]:
# -----------------------------
# 3. TRANSPOSE
# -----------------------------
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
            0     1      2     3
Student  Ali  Sara  Bilal  Hina
Marks     85    92     76    89
Age       20    21     19    22

## Slicing through loc function

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
     Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [ ]:
# 1. Select row with label 2
print(df.loc[2])

Name     Bilal
Marks       76
Age         19
Name: 2, dtype: object

In [ ]:
# 2. Select specific rows and columns by NAME
print(df.loc[1:3, ["Name", "Marks"]])

    Name  Marks
1   Sara     92
2  Bilal     76
3   Hina     89

In [ ]:

# 3. Applying Filter: Conditional selection: students with Marks > 85
print(df.loc[df["Marks"] > 85])

   Name  Marks  Age
1  Sara     92   21
3  Hina     89   22

##  Slicing through iloc

In [ ]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [ ]:
# 1. Select row at index 0
print(df.iloc[0])

Name     Ali
Marks     85
Age       20
Name: 0, dtype: object

In [ ]:
# 2. Select 2 rows and 2 columns by position
print(df.iloc[0:2, 0:2])

   Name  Marks
0   Ali     85
1  Sara     92

In [ ]:
# 3. Select last row using negative index
print(df.iloc[-1])

Name     Hina
Marks      89
Age        22
Name: 3, dtype: object

# Dropping the Row

In [ ]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [ ]:
df.drop(0).head()

    Name  Marks  Age
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

# Dropping the col

In [ ]:
df.drop(['Age'], axis=1).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [ ]:
df.head()

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [ ]:
df.drop(['Age'], axis=1, inplace=True)

In [ ]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [ ]:
df.reset_index().head()

   index   Name  Marks
0      0    Ali     85
1      1   Sara     92
2      2  Bilal     76
3      3   Hina     89

In [ ]:
df.reset_index(drop=True).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [ ]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [ ]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [ ]:
df.groupby('Company')

##### You can save this object as a new variable:

In [ ]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.core.groupby.generic.DataFrameGroupBy

#### And then call aggregate methods of the object:

In [ ]:
by_comp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
df.groupby('Company').mean()

In [ ]:
by_comp.std()

In [ ]:
by_comp.min()

In [ ]:
by_comp.max()

In [ ]:
by_comp.count()

In [ ]:
by_comp.describe()